# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7af6d7d336dbcdddb8322bb3c08a59e48df84d30e09d3b1d0e6509db3b772491859c6affbab1343928b2f9fde7a92d5c74f25900bf0b009fba721bf4ce035c7

test:
  secret_key_base: ab3932f0a62f926ac73bfe11a7dd2271f375c4b6c1653963501338450e0531fd824ecfc1b98a581a4872010fc2e37c3823a7438cc28c58fd66036ecf97e213b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
